### ISSUE TITLE
Running Frankencover script on Jenkins

### ISSUE THREAD

**Issue by siddharthan64** [appsquickly/frankencover.it#26]
The coverage.info holds the wrong source file destination. I created a Project A and run the Frankencover script locally. Then deleted the project and created Project B. This time the coverage.info files SN: value is pointing to the file that belongs to project A. Has anyone come across this issue?

geninfo ./build/reports/temp/coverage-data/*.gcno  --output-filename ./build/reports/temp/coverage.info.temp || :
lcov -r ./build/reports/temp/coverage.info.temp main.m queue.h once.h CGGeometry.h MKGeometry.h NSRange.h > ./build/reports/temp/coverage.info

**Comment by siddharthan64** [comment]
I guess its picking up from the DerivedData folder. can someone confirm on this?

**Comment by jasperblues** [comment]
@siddharthan64 Sounds like a possible error. Because build output for a particular app can end up in an unpredictably (so far as I know) named folder, it uses unix cmds to scan that entire root folder for data-files corresponding to the name of one of your files in the specified source dir. . So if you have two projects with classes named the same this problem could occur. 

**Workaround:**

Before running the build you could `rm -fr ~/Library/Developer/Xcode/DerivedData` - there should be no negative impacts to this beyond a slightly slower build, but on the plus side it would give more reliable results overall, not just for coverage.
